name: Pipeline QA API Provas

on:
  pull_request:
    - main
    - develop

jobs:

  health_check:
    name: Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 177
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Testes de Health Check
        run: mvn test -Dgroups="Health-Check"
        continue-on-error: false
        id: healthcheck

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L "https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz"
          tar -zxvf allure.tgz
          sudo mv allure-2.20.1 /usr/local/bin/allure
          sudo ln -s /usr/local/bin/allure/bin/allure /usr/bin/allure

      - name: Upload resultados Health Check
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
