name: Pipeline QA API Provas

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:

  health_check:
    name: Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodando testes de Health Check
        run: mvn test -Dgroups="Health-Check"
        continue-on-error: false
        id: healthcheck

  generate_report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: health_check

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Edit index.html to include GitHub Run ID
        run: |
          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=https://estudos-github-actions.vercel.app/${{ github.run_number }}/index.html\">" | sudo tee allure-history/index.html > /dev/null
          echo "<meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\">" | sudo tee -a allure-history/index.html > /dev/null

      - name: Debug index.html
        run: |
          cat allure-history/index.html

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  python_test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    needs: health_check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script with webhook key
        run: |
          python screenshot.py
        env:
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
