name: Pipeline QA API Provas

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:

  health_check:
    name: Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Testes de Health Check
        run: mvn test -Dgroups="Health-Check"
        continue-on-error: false
        id: healthcheck

      - name: Upload resultados Health Check
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  deploy_report:
    name: Allure Report
    runs-on: ubuntu-latest
    needs: health_check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure reports
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L "https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz"
          tar -zxvf allure.tgz
          sudo mv allure-2.20.1 /usr/local/bin/allure
          sudo ln -s /usr/local/bin/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Install Node.js and http-server locally
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install http-server

      - name: Start HTTP server to host Allure report
        run: |
          npx http-server allure-report -p 8080 &
          sleep 5

  deploy_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: deploy_report

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Copy Allure report to gh-pages
        run: |
          git fetch --depth=1 origin gh-pages || git checkout --orphan gh-pages
          git reset
          git rm -rf .
          cp -r allure-report/* .
          git add .
          git commit -m "Deploy Allure Report"
          git push origin gh-pages --force

